Exercise 11.

In [1]:
from transformers import TFOpenAIGPTLMHeadModel

model = TFOpenAIGPTLMHeadModel.from_pretrained('openai-gpt')

All model checkpoint layers were used when initializing TFOpenAIGPTLMHeadModel.

All the layers of TFOpenAIGPTLMHeadModel were initialized from the model checkpoint at openai-gpt.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFOpenAIGPTLMHeadModel for predictions without further training.


In [2]:
from transformers import OpenAIGPTTokenizer

tokenizer = OpenAIGPTTokenizer.from_pretrained('openai-gpt')

ftfy or spacy is not installed using BERT BasicTokenizer instead of SpaCy & ftfy.


In [3]:
prompt_text = 'This royal throne of kings, this sceptred isle'
encoded_prompt = tokenizer.encode(prompt_text, 
                                  add_special_tokens=False, 
                                  return_tensors='tf')
encoded_prompt

<tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187]])>

In [4]:
num_sequences = 5
length = 40

generated_sequences = model.generate(
    input_ids=encoded_prompt,
    do_sample=True,
    max_length=length + len(encoded_prompt[0]),
    temperature=1.0,
    top_k=0,
    top_p=0.9,
    repetition_penalty=1.0,
    num_return_sequences=num_sequences,
)

generated_sequences

<tf.Tensor: shape=(5, 50), dtype=int32, numpy=
array([[  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   239,   568,   895,   587,   600,   966,   525,  2455,
          500,   481,   929,  1082,   257,   256, 40477,   256,  3369,
          600,   587,   538,   823,   704,  3354,   498,   688,   240,
          256,   481,  1002,   603,   239, 40477,   256,   249,  1259,
          799,   651,   485,   547,  1158],
       [  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   267,   485,   925,   575,  4385,   240,   512,   759,
          595,   239,   568,   606,   604,   485,   825,   498,   575,
          267,   488,   507,  1259,   580,  1256,  6465,   239,   507,
          544,   595,   870,   525,  1288,  1175, 20128,   481,   618,
          498,   481, 34251,  7455,   240],
       [  616,  5751,  6404,   498,  9606,   240,   616, 26271,  7428,
        16187,   240,   498,   589,  3142,   240,   488,   616,  1813,
          240

In [5]:
for sequence in generated_sequences:
    text = tokenizer.decode(sequence, clean_up_tokenization_sapeces=True)
    print(text)
    print('-' * 100)

this royal throne of kings, this sceptred isle. but why do they need that tree in the first place?'
'surely they don't want your knowledge of them,'the voice said. 
'i must go back to my father
----------------------------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle! to make him stronger, you can not. but we have to think of him! and it must be done swiftly. it is not good that these men slay the king of the accursed empire,
----------------------------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle, of all places, and this ring, whoever gave it to me, and this much - priceless piece of the queen, so that after that three months i might speak to thee in my own way
----------------------------------------------------------------------------------------------------
this royal throne of kings, this sceptred isle. if any one of these pretentious